unpackaged/objects/USSI_Student__c.object
<CustomObject>
    <fields>
        <fullName>USSI_Degree_Program__c</fullName>
        <label>Degree Program</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>USSI_Email_Address__c</fullName>
        <label>Email Address</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>USSI_Expected_Graduation__c</fullName>
        <label>Expected Graduation</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>USSI_First_Name__c</fullName>
        <label>First Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>USSI_Last_Name__c</fullName>
        <label>Last Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>USSI_Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>USSI_Preferred_Contact__c</fullName>
        <label>Preferred Contact Method</label>
        <picklist>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voice</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>USSI_TimeStamp__c</fullName>
        <description>If this field is updated, send an email to the student</description>
        <inlineHelpText>When is the last verification email sent</inlineHelpText>
        <label>Last Sent</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>USSI_University__c</fullName>
        <label>University</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>USSI_Verification_Code__c</fullName>
        <label>Verification Code</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Student Intern</label>
    <nameField>
        <displayFormat>STU-{0000}</displayFormat>
        <label>Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Interns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/TEST_USSI_Verification_Code.cls
@isTest
public class TEST_USSI_Verification_Code {
    //create user of sys admin
    static User getUser(){
        Profile profileId = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User u = new user();
        u.LastName = 'Test Coe';
        u.Email = 'test1@test.com';
        u.Alias = 'Tcode';
        u.Username = 'test123434@test.com';
        u.CommunityNickname = 'test122';
        u.LocaleSidKey = 'en_US';
        u.ProfileId = profileId.Id;
        u.TimeZoneSidKey = 'GMT';
        u.LanguageLocaleKey = 'en_US';
        u.EmailEncodingKey = 'UTF-8';
        insert u;
        return u;
    }
    
    //Basic test to test sending a single email
    static testmethod void testEmailOnDeferred(){
        User u = getUser();
        System.runAs(u){
            
            Test.startTest();
            Integer emailbefore = Limits.getEmailInvocations();
            USSI_Student__c student_intern = 
                new USSI_Student__c(USSI_First_Name__c='Test Data', USSI_Last_Name__c='Test Data',
                                    USSI_University__c='Test Data', USSI_Degree_Program__c='Test Data',
                                    USSI_Email_Address__c='test@example.com', USSI_Phone_Number__c='075444444444',
                                    USSI_Preferred_Contact__c='Email', USSI_Expected_Graduation__c=Date.today(),
                                    USSI_Verification_Code__c=12345, USSI_TimeStamp__c=Date.today());
            insert student_intern;
            //update timestamp to trigger the apex
            student_intern.USSI_TimeStamp__c = Date.today().addMonths(1); 
            update student_intern;
            System.assertEquals(emailbefore+1, Limits.getEmailInvocations());
            Test.stopTest();
        }
    }
    
    //Advance test to send email to multiple people
    static testmethod void testMassEmailSending(){
        User u = getUser();
        System.runAs(u){
            Integer emailbefore = Limits.getEmailInvocations();
            Test.startTest();
            //Number of times to invoke trigger
            for(Integer j = 0; j < 5; j++){
                List<USSI_Student__c> students = new List<USSI_Student__c>();
                //Number of emails sent per trigger
                for(Integer i = 0; i < 10; i++){
                    USSI_Student__c student_intern = 
                        new USSI_Student__c(USSI_First_Name__c='Test Data', USSI_Last_Name__c='Test Data',
                                            USSI_University__c='Test Data', USSI_Degree_Program__c='Test Data',
                                            USSI_Email_Address__c='test@example.com', USSI_Phone_Number__c='075444444444',
                                            USSI_Preferred_Contact__c='Email', USSI_Expected_Graduation__c=Date.today(),
                                            USSI_Verification_Code__c=12345, USSI_TimeStamp__c=Date.today());
                    insert student_intern;
                    //update timestamp to trigger the apex
                    student_intern.USSI_TimeStamp__c = Date.today().addMonths(1);
                    students.add(student_intern);
                }
                update students;
            }
            
            //Invocation is incremented per trigger invoke
            System.assertEquals(emailbefore+5, Limits.getEmailInvocations());
            Test.stopTest();
        }
    }
}